---
include:
  - project: "ctek/gitlab/pipeline/templates"
    ref: ${PIPELINE_TEMPLATES_VERSION_LATEST}
    file:
      - linting/all-linters.yml
      - workflow/all-workflow.yml

variables:
  ANSIBLE_IMAGE: $CI_REGISTRY/ctek/docker/ansible

workflow:
  rules:
    - if: $CI_PROJECT_ID != '7443'
      when: never
    - when: always

.rules_not_on_merge_request: &rules_not_on_merge_request
  if: $CI_MERGE_REQUEST_ID
  when: never

.rules_not_on_tags: &rules_not_on_tags
  if: $CI_COMMIT_TAG
  when: never

.rules_not_on_semantic_release: &rules_not_on_semantic_release
  if: '$CI_COMMIT_MESSAGE =~ /^chore\(release\).*/'
  when: never


stages:
  - release


semantic-release:
  stage: release
  extends: .semantic-release-template
  rules:
    - *rules_not_on_tags
    - *rules_not_on_merge_request
    - *rules_not_on_semantic_release
    - if: $CI_COMMIT_BRANCH =~ /^(ctek-main|ctek-development)$/
      when: on_success
